### ISSUE TITLE
off-topic: modifica nel footer dei messaggi in mailing list

### ISSUE THREAD

**Issue by aborruso** [spaghetti-open-data/website#1]
Ciao,
mi piacerebbe che nel footer di ogni messaggio inviato in mailing list, ci fosse anche il permalink al messaggio. Al momento c'è solo l'URL generale della mailing list.
Io lo trovo molto comodo per "saltare" _on topic_ e per condividere un thread verso altri "spazi".

![image](https://cloud.githubusercontent.com/assets/30607/23834940/07272490-075f-11e7-9b36-4df071131f5c.png)

**Comment by albertocottica** [comment]
Ascolto e obbedisco. Vedi se funziona, ma almeno Google queste cose non dovrebbe sbagliarle. :-)

**Comment by aborruso** [comment]
Grazie mille
